FILES = main.c\
		1_initpointeur.c\
		2_tableaudynamique.c\
		3_strlen.c\
		4_strcopy.c\
		5_strdup.c\
		6_strcat.c\
		7_strfind.c\
		8_strinvert.c

TARGET = chipolatata
all :
	gcc ${FILES} -o ${TARGET}


# regle : condition 
run :${TARGET} 
	./${TARGET}

clean :
	rm -rf ${TARGET}